const Section = ({ title, children }) => (
  <div className="mb-8">
    <h2 className="text-lg font-bold text-slate-900 mb-3">{title}</h2>
    <div className="text-slate-500 text-sm leading-relaxed space-y-2">{children}</div>
  </div>
);

const Terms = () => (
  <div className="bg-white min-h-screen pt-24 pb-20 px-4">
    <div className="max-w-3xl mx-auto">
      <div className="mb-12">
        <span className="inline-block bg-teal-50 text-teal-700 text-xs font-semibold tracking-widest uppercase px-3 py-1 rounded-full border border-teal-200 mb-4">Legal</span>
        <h1 className="text-4xl font-extrabold text-slate-900 mb-3">Terms of Service</h1>
        <p className="text-slate-400 text-sm">Last updated: January 2025</p>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 mb-10">
        <p className="text-amber-800 text-sm font-medium">
          Important: PranixAI provides preliminary health information only. It is not a substitute for professional medical diagnosis or treatment. Always consult a qualified healthcare professional.
        </p>
      </div>

      <Section title="1. Acceptance of terms">
        <p>By accessing or using PranixAI, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>
      </Section>

      <Section title="2. Description of service">
        <p>PranixAI is a free AI-powered preliminary health assessment platform. It allows users to describe symptoms via text, voice, or image and receive AI-generated health information. It also provides nearby doctor discovery and appointment booking functionality.</p>
      </Section>

      <Section title="3. Medical disclaimer">
        <p>PranixAI is NOT a medical device, does NOT provide medical diagnosis, and is NOT a substitute for professional medical advice, diagnosis, or treatment.</p>
        <p>All content generated by PranixAI is for informational purposes only. Always seek the advice of a qualified physician for any medical condition. Never disregard professional medical advice because of something you read on PranixAI.</p>
        <p>In case of a medical emergency, call emergency services immediately.</p>
      </Section>

      <Section title="4. User responsibilities">
        <p>You must provide accurate information when registering. You are responsible for maintaining the security of your account. You agree not to use PranixAI for any unlawful purpose.</p>
      </Section>

      <Section title="5. Intellectual property">
        <p>PranixAI, its logo, interface, and all associated content are the intellectual property of Aryan Maurya. You may not reproduce, distribute, or create derivative works without written permission.</p>
      </Section>

      <Section title="6. Limitation of liability">
        <p>PranixAI is provided "as is" without warranties of any kind. To the fullest extent permitted by law, Aryan Maurya shall not be liable for any indirect, incidental, or consequential damages arising from the use of PranixAI.</p>
      </Section>

      <Section title="7. Changes to terms">
        <p>We reserve the right to modify these terms at any time. Continued use of PranixAI after changes constitutes acceptance of the new terms.</p>
      </Section>

      <Section title="8. Contact">
        <p>For questions about these terms, contact us via the <a href="/contact" className="text-teal-600 hover:underline">Contact page</a>.</p>
      </Section>
    </div>
  </div>
);

export default Terms;